spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    username: postgres
    password: code123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
